package com.guofei.other.compress;

import com.guofei.JsonUtils;
import com.guofei.other.compress.example.CalendarEvent;
import com.guofei.other.compress.example.CalendarEventRoom;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import sun.misc.BASE64Decoder;
import sun.misc.BASE64Encoder;

/**
 * @author: GuoFei
 * @date: 2022-03-13 19:21
 */
public class CompressMain {

  public static void main(String[] args) throws Exception {
    String s = getString();
    System.out.println(s);
    System.out.println("字符串长度："+s.length());
    String gzip = GZIPUtils.gzip(s);
    // String gzip = "H4sIAI4Q8GAA/8utDC4pysxlBwDH6ex/CAAAAA==";
    System.out.println("压缩后字符串长度：："+gzip.length());
    System.out.println("压缩后字符串：："+gzip);

    String gunzip = GZIPUtils.gunzip(gzip);
    System.out.println("解缩后字符串长度：："+gunzip.length());
    System.out.println("解缩后字符串：："+gunzip);
  }


  /**
   *
   * @return Map<String, List<CalendarEvent>>
   */
  private static String getMap(){
    List<CalendarEvent> list0 = new ArrayList();
    CalendarEvent event = new CalendarEvent();
    event.setAllDay(1);
    CalendarEventRoom eventRoom = new CalendarEventRoom();
    eventRoom.setRoomId(1);
    CalendarEventRoom eventRoom1 = new CalendarEventRoom();
    eventRoom1.setRoomId(1);
    List list = new ArrayList();
    list.add(eventRoom);
    list.add(eventRoom1);
    event.setCalendarEventRooms(list);
    event.setCalendarEventRooms(list);
    list0.add(event);
    list0.add(event);
    Map<String,List<CalendarEvent>> map =new HashMap();
    map.put("2022-3-17",list0);
    map.put("2022-3-18",list0);
    // System.out.println(map);
    String s = JsonUtils.toString(map);
    return s;
  }
  private static String getMap1(){
    List<CalendarEvent> list0 = new ArrayList();
    Map<String,List<CalendarEvent>> map =new HashMap();
    CalendarEvent event = new CalendarEvent();
    event.setAllDay(1);
    list0.add(event);
    map.put("2022-3-17",list0);
    String s = JsonUtils.toString(map);
    return s;
  }

  private static String getMap2(){
    Map<String,Object> map =new HashMap();
    map.put("k1",11);
    map.put("k2",22);
    String s = JsonUtils.toString(map);
    return s;
  }


  public static String byteToString(byte [] bytes){
    return new BASE64Encoder().encodeBuffer(bytes);
  }
  public static byte [] stringToBytes(String  string) throws IOException {
    return new BASE64Decoder().decodeBuffer(string);
  }

  public static String getString(){
    String aa = "{\n"
        + "    \"returncode\": 200,\n"
        + "    \"message\": \"成功\",\n"
        + "    \"result\": {\n"
        + "        \"2022-3-19\": [\n"
        + "            {\n"
        + "                \"id\": 93872,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-19 22:15:01\",\n"
        + "                \"endTime\": \"2022-03-19 22:30:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647699301000,\n"
        + "                \"endTimeStamp\": 1647700200000,\n"
        + "                \"createTime\": \"2021-12-31 17:21:22\",\n"
        + "                \"meetingDay\": 1647619200000,\n"
        + "                \"modifiyTime\": 1640942443000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"9035d938-4072-4bcf-9519-7d541ac2c164_79\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"9035d938-4072-4bcf-9519-7d541ac2c164\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-19\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494434941,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647697801000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609076,\n"
        + "                        \"calendarEventId\": 93872,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:21:23\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:21:23\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942443000\n"
        + "            },\n"
        + "            {\n"
        + "                \"id\": 94052,\n"
        + "                \"caleTitle\": \"test\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-19 23:00:01\",\n"
        + "                \"endTime\": \"2022-03-20 01:00:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 120,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647702001000,\n"
        + "                \"endTimeStamp\": 1647709200000,\n"
        + "                \"createTime\": \"2021-12-31 17:28:52\",\n"
        + "                \"meetingDay\": 1647619200000,\n"
        + "                \"modifiyTime\": 1640942887000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778_79\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-19\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494875463,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647700501000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609284,\n"
        + "                        \"calendarEventId\": 94052,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:28:53\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:28:53\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942887000\n"
        + "            }\n"
        + "        ],\n"
        + "        \"2022-3-18\": [\n"
        + "            {\n"
        + "                \"id\": 93869,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-18 22:15:01\",\n"
        + "                \"endTime\": \"2022-03-18 22:30:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647612901000,\n"
        + "                \"endTimeStamp\": 1647613800000,\n"
        + "                \"createTime\": \"2021-12-31 17:21:21\",\n"
        + "                \"meetingDay\": 1647532800000,\n"
        + "                \"modifiyTime\": 1640942443000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"9035d938-4072-4bcf-9519-7d541ac2c164_78\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"9035d938-4072-4bcf-9519-7d541ac2c164\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-18\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494434941,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647611401000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609073,\n"
        + "                        \"calendarEventId\": 93869,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:21:22\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:21:22\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942443000\n"
        + "            },\n"
        + "            {\n"
        + "                \"id\": 94050,\n"
        + "                \"caleTitle\": \"test\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-18 23:00:01\",\n"
        + "                \"endTime\": \"2022-03-19 01:00:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 120,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647615601000,\n"
        + "                \"endTimeStamp\": 1647622800000,\n"
        + "                \"createTime\": \"2021-12-31 17:28:51\",\n"
        + "                \"meetingDay\": 1647532800000,\n"
        + "                \"modifiyTime\": 1640942887000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778_78\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-18\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494875463,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647614101000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609281,\n"
        + "                        \"calendarEventId\": 94050,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:28:52\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:28:52\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942887000\n"
        + "            }\n"
        + "        ],\n"
        + "        \"2022-3-20\": [\n"
        + "            {\n"
        + "                \"id\": 93875,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-20 22:15:01\",\n"
        + "                \"endTime\": \"2022-03-20 22:30:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647785701000,\n"
        + "                \"endTimeStamp\": 1647786600000,\n"
        + "                \"createTime\": \"2021-12-31 17:21:23\",\n"
        + "                \"meetingDay\": 1647705600000,\n"
        + "                \"modifiyTime\": 1640942443000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"9035d938-4072-4bcf-9519-7d541ac2c164_80\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"9035d938-4072-4bcf-9519-7d541ac2c164\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-20\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494434941,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647784201000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609079,\n"
        + "                        \"calendarEventId\": 93875,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:21:24\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:21:24\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942443000\n"
        + "            },\n"
        + "            {\n"
        + "                \"id\": 94055,\n"
        + "                \"caleTitle\": \"test\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-20 23:00:01\",\n"
        + "                \"endTime\": \"2022-03-21 01:00:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 120,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647788401000,\n"
        + "                \"endTimeStamp\": 1647795600000,\n"
        + "                \"createTime\": \"2021-12-31 17:28:53\",\n"
        + "                \"meetingDay\": 1647705600000,\n"
        + "                \"modifiyTime\": 1640942887000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778_80\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-20\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494875463,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647786901000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609287,\n"
        + "                        \"calendarEventId\": 94055,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:28:54\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:28:54\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942887000\n"
        + "            }\n"
        + "        ],\n"
        + "        \"2022-3-15\": [\n"
        + "            {\n"
        + "                \"id\": 93860,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-15 22:15:01\",\n"
        + "                \"endTime\": \"2022-03-15 22:30:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647353701000,\n"
        + "                \"endTimeStamp\": 1647354600000,\n"
        + "                \"createTime\": \"2021-12-31 17:21:18\",\n"
        + "                \"meetingDay\": 1647273600000,\n"
        + "                \"modifiyTime\": 1640942443000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"9035d938-4072-4bcf-9519-7d541ac2c164_75\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"9035d938-4072-4bcf-9519-7d541ac2c164\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-15\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494434941,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647352201000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609064,\n"
        + "                        \"calendarEventId\": 93860,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:21:19\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:21:19\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942443000\n"
        + "            }\n"
        + "        ],\n"
        + "        \"2022-3-14\": [\n"
        + "            {\n"
        + "                \"id\": 108540,\n"
        + "                \"caleTitle\": \"即时会议\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-14 22:06:10\",\n"
        + "                \"endTime\": \"2022-03-14 22:21:09\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647266770789,\n"
        + "                \"endTimeStamp\": 1647267669789,\n"
        + "                \"createTime\": \"2022-03-14 22:06:19\",\n"
        + "                \"meetingDay\": 1647187200000,\n"
        + "                \"modifiyTime\": 1647266780000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"045084e3-0e22-4f83-b13a-2e3a2f86aadc\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[]\",\n"
        + "                \"organizer\": \"\",\n"
        + "                \"userId\": 0,\n"
        + "                \"checkAll\": 1,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": null,\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-14\",\n"
        + "                \"recurrenceSetting\": null,\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 2,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647265270789,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 0,\n"
        + "                \"openApply\": 1,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": null,\n"
        + "                \"calendarEventAttendees\": [],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1647266780000\n"
        + "            },\n"
        + "            {\n"
        + "                \"id\": 108536,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-14 22:45:01\",\n"
        + "                \"endTime\": \"2022-03-14 23:00:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647269101000,\n"
        + "                \"endTimeStamp\": 1647270000000,\n"
        + "                \"createTime\": \"2022-03-14 21:43:13\",\n"
        + "                \"meetingDay\": 1647187200000,\n"
        + "                \"modifiyTime\": 1647265394000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"48d569e9-ddcb-428a-9114-bb3bd00acb8a\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"ningchanglong@mushi.ai\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"ningchanglong@mushi.ai\",\n"
        + "                \"userId\": 1876,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": null,\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-14\",\n"
        + "                \"recurrenceSetting\": null,\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 1647269401000,\n"
        + "                \"beginCheckInTime\": 1647267601000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 0,\n"
        + "                \"openApply\": 1,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"宁长龙\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1821948,\n"
        + "                        \"calendarEventId\": 108536,\n"
        + "                        \"userId\": 1876,\n"
        + "                        \"email\": \"ningchanglong@mushi.ai\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"宁长龙\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2022-03-14 21:43:14\",\n"
        + "                        \"modifiyTime\": \"2022-03-14 21:43:14\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1647265394000\n"
        + "            },\n"
        + "            {\n"
        + "                \"id\": 108537,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-14 23:15:01\",\n"
        + "                \"endTime\": \"2022-03-14 23:30:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647270901000,\n"
        + "                \"endTimeStamp\": 1647271800000,\n"
        + "                \"createTime\": \"2022-03-14 21:44:04\",\n"
        + "                \"meetingDay\": 1647187200000,\n"
        + "                \"modifiyTime\": 1647265445000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"0ea2df0b-5062-47cc-a2f1-33ecffb18e9e\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"ningchanglong@mushi.ai\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"ningchanglong@mushi.ai\",\n"
        + "                \"userId\": 1876,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": null,\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-14\",\n"
        + "                \"recurrenceSetting\": null,\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 1647271201000,\n"
        + "                \"beginCheckInTime\": 1647269401000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 0,\n"
        + "                \"openApply\": 1,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"宁长龙\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1821949,\n"
        + "                        \"calendarEventId\": 108537,\n"
        + "                        \"userId\": 1876,\n"
        + "                        \"email\": \"ningchanglong@mushi.ai\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"宁长龙\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2022-03-14 21:44:05\",\n"
        + "                        \"modifiyTime\": \"2022-03-14 21:44:05\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1647265445000\n"
        + "            }\n"
        + "        ],\n"
        + "        \"2022-3-17\": [\n"
        + "            {\n"
        + "                \"id\": 93866,\n"
        + "                \"caleTitle\": \"无主题\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-17 22:15:01\",\n"
        + "                \"endTime\": \"2022-03-17 22:30:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 15,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647526501000,\n"
        + "                \"endTimeStamp\": 1647527400000,\n"
        + "                \"createTime\": \"2021-12-31 17:21:20\",\n"
        + "                \"meetingDay\": 1647446400000,\n"
        + "                \"modifiyTime\": 1640942443000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"9035d938-4072-4bcf-9519-7d541ac2c164_77\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"9035d938-4072-4bcf-9519-7d541ac2c164\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-17\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494434941,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647525001000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609070,\n"
        + "                        \"calendarEventId\": 93866,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:21:21\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:21:21\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942443000\n"
        + "            },\n"
        + "            {\n"
        + "                \"id\": 94047,\n"
        + "                \"caleTitle\": \"test\",\n"
        + "                \"caleDes\": \"\",\n"
        + "                \"beginTime\": \"2022-03-17 23:00:01\",\n"
        + "                \"endTime\": \"2022-03-18 01:00:00\",\n"
        + "                \"demoData\": false,\n"
        + "                \"duration\": 120,\n"
        + "                \"roomId\": 6188,\n"
        + "                \"roomName\": null,\n"
        + "                \"syncRoomEmail\": \"\",\n"
        + "                \"syncRoomIdentity\": \"\",\n"
        + "                \"syncRoomName\": \"\",\n"
        + "                \"companyId\": 195,\n"
        + "                \"meetingType\": 4,\n"
        + "                \"beginTimeStamp\": 1647529201000,\n"
        + "                \"endTimeStamp\": 1647536400000,\n"
        + "                \"createTime\": \"2021-12-31 17:28:50\",\n"
        + "                \"meetingDay\": 1647446400000,\n"
        + "                \"modifiyTime\": 1640942887000,\n"
        + "                \"isDel\": 0,\n"
        + "                \"calendarIdentity\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778_77\",\n"
        + "                \"userCalendarId\": \"\",\n"
        + "                \"requiredAttendees\": \"[{\\\"id\\\":0,\\\"calendarEventId\\\":0,\\\"userId\\\":0,\\\"email\\\":\\\"liuyang@vision-iot.co\\\",\\\"acceptStatus\\\":0,\\\"displayName\\\":\\\"\\\",\\\"resource\\\":0,\\\"createTime\\\":null,\\\"modifiyTime\\\":null,\\\"isDel\\\":0,\\\"checkin\\\":0,\\\"pageId\\\":null}]\",\n"
        + "                \"organizer\": \"liuyang@vision-iot.co\",\n"
        + "                \"userId\": 1733,\n"
        + "                \"checkAll\": 0,\n"
        + "                \"meetingStatus\": 0,\n"
        + "                \"selfCalendarEvent\": false,\n"
        + "                \"enableEdit\": 0,\n"
        + "                \"timeZone\": \"Asia/Shanghai\",\n"
        + "                \"roomStatus\": 1,\n"
        + "                \"roomType\": 832,\n"
        + "                \"isBindZoom\": 0,\n"
        + "                \"groupIds\": null,\n"
        + "                \"recurringEventId\": \"47a3e2ac-b53a-4414-8d14-1664fe93e778\",\n"
        + "                \"recurringDate\": null,\n"
        + "                \"allDay\": 0,\n"
        + "                \"monthday\": \"2022-3-17\",\n"
        + "                \"recurrenceSetting\": \"{\\\"recurrenceEnumType\\\":\\\"DAILY\\\",\\\"count\\\":null,\\\"until\\\":1656494875463,\\\"interval\\\":0,\\\"weekDays\\\":null,\\\"byMonthDays\\\":null,\\\"byYearDays\\\":null,\\\"byMonty\\\":null}\",\n"
        + "                \"reminders\": \"\",\n"
        + "                \"reminderList\": null,\n"
        + "                \"source\": 0,\n"
        + "                \"checkInName\": \"\",\n"
        + "                \"cancelTime\": 0,\n"
        + "                \"beginCheckInTime\": 1647527701000,\n"
        + "                \"calendarEventRooms\": null,\n"
        + "                \"eventType\": 1,\n"
        + "                \"openApply\": 0,\n"
        + "                \"applyStatus\": 1,\n"
        + "                \"externalRoomsType\": 0,\n"
        + "                \"externalRoomsEventId\": null,\n"
        + "                \"addTcentMeet\": 1,\n"
        + "                \"organizerNikeName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                \"calendarEventAttendees\": [\n"
        + "                    {\n"
        + "                        \"id\": 1609279,\n"
        + "                        \"calendarEventId\": 94047,\n"
        + "                        \"userId\": 1733,\n"
        + "                        \"email\": \"liuyang@vision-iot.co\",\n"
        + "                        \"acceptStatus\": 0,\n"
        + "                        \"displayName\": \"刘杨刘杨刘杨刘杨刘杨刘杨刘杨刘杨\",\n"
        + "                        \"resource\": 0,\n"
        + "                        \"createTime\": \"2021-12-31 17:28:51\",\n"
        + "                        \"modifiyTime\": \"2021-12-31 17:28:51\",\n"
        + "                        \"isDel\": 0,\n"
        + "                        \"checkin\": 0,\n"
        + "                        \"pageId\": null\n"
        + "                    }\n"
        + "                ],\n"
        + "                \"remoteUpdated\": null,\n"
        + "                \"needCheck\": true,\n"
        + "                \"updateTimeStamp\": 1640942887000\n"
        + "            }\n"
        + "        ]\n"
        + "    },\n"
        + "    \"success\": true\n"
        + "}";
    return aa;
  }


  public static String getString2(){
    String aa = "H4sIAAAAAAAAAO2cW2/bNhTHv0qgZ3vjVaT8kmVNHgK0fVi7h7YeBkWiE6Gy5OnSzQvy3XdISbbs\n"
        + "WpHqxY4tu0CC8CqS5/D8/CflPlqJyvIk8mJfWSOC0MCaqjR17yFlpbnnQcIaQKU0DzNr9GgRRMiQ\n"
        + "DrFjjb48WoFvjRwqBRlYnhuqj0EW6oaXl5dWkXOtUkhD4k7dB9HHYKqLTR9Id3JByAjzEcJQQ0X+\n"
        + "xnKKRghBua+m8bWbudZo4oapgow8cbMgjizoAoYYx9NbGI6NpSxS713dW5SH4cBK55H3G+TdTN0g\n"
        + "LEZUZd36KsqCbL6aWzTWOV48nbnRXPeNHa7XR2VBdP9xPoMKrDazD5k7nUElmwnbcSjCSC9nOa1a\n"
        + "oUAIFtoUeolyM7WcNh5iWF18gcWI4BEh1uJx1+687Bo7Vetp7AeTYF40hzLkMMIYNWVBeq1goqgw\n"
        + "Q+S7SW2eDqLcB7sNGRJkyO68ydDh2BkKnzPsesSDzv4UDjw9T1XyZtFBsSCJ+isPEuVfZRnkK2Ph\n"
        + "L49jcIaxfuB48cSbb/DE2ypXd7VIKG0H+HtshUE+d6P7X74FKdhyGMTZT148tqCOC943y2Dhsjwt\n"
        + "m/lBOgvduTaOaWzqgXPGeeKp6umLNR2X1h/XV2qZaZaoavSgvK9BVKZm4P9mqLrm0x8w5zi5d6Pg\n"
        + "X5XAXDeOuFwr4yWC0kHR41VY2KA0YjEXk5OqcPKmvk4Lt1aRexeqGz/ITMUMxvw5jrSDXKWB+/OH\n"
        + "B3j2gxtYhZNXXeIiWXilpER7wK9B5H+GTNPPfRLns1s/rXZEorw8SWBQpZU6uoVVawm7cbHB3DA0\n"
        + "LmrcMsoefJ2oRYuqmYo89UFlejWg/HFcy76JcjN+Y9nrq9u3n4x5vTiPsqXVIGE8B9vcZg64O/zC\n"
        + "2ppRppJvbmXQv5X6CgNKlw3v5u/0wNYzPyk32VRxXpnfDH0KS6mStNoARfJtkGaLAGNcsNhw2vK3\n"
        + "US2CuDC7sNimqAwYb4pKi70LIUPIMmSs7B8djBZGUzqnsDEYPJ6p6Go2C4tld/VfNXdQ/8CCRG5o\n"
        + "OijaoLXchelLG/r+Rw9y3oG3Fg+ovP598FWV87lc+2etjbcWFUpAYBs5SNiD9biwQMfqxlFliG7a\n"
        + "ZvWwYKZUCwqbx1cFiMI6z4dcaq3F1YY6tfhahA7zdxE4qrhhPCXO1O8zHx65WOZIKd+Y3xplSQ47\n"
        + "Pjflq5RYxvKnQclZhvgaZzMFDtgRtBQo2gRagi4QNuVtoCXowEgrNEubSet0Ia0c8S1IK6VoJy0T\n"
        + "LlXE9YZ3nLpDxjAbSh9+YdtmE+VQJYQ8k/bkSNvFLQ6NtFJwZtMekBa2Le8vaYlkm0hbwONgSAsh\n"
        + "t5W0ZZ19kLaI5bqfah/Jur61ne30rWzRt/Jo9S0mTiN1bUxlN32LN1CXUyL3o2/lmbqnRd3d6Vu5\n"
        + "M+r2R99izPpLXSToZn2r0XEw1K2OFFv0LXk1fYu21LfyeX0L+vdY9a2Nud1MWkK6kBY+SG1B2hfU\n"
        + "t2fSnhhpd6dvd0fa3uhbGzPcX9ISiRv0LTog0lZHii36dl+k/U7fErRyf8u30rcEPa9vi/Jj1LdC\n"
        + "ctF8qixtu5u+pRuoKxC396JvJTpT97SouzN9S9BZ37aeKktG+ktdJJyG+1t+QNSFkMs66Fv2avqW\n"
        + "b6dvNUifvb/FR6tvhZSsmbQO70La6jLhx0j7cvr2TNpTI+3O9O0OSdsbfQufv53+kpZI0aBvD4m0\n"
        + "EHJbSVvWeZ37W75yf4u20reYt9zf8mPVt5TTZn1LIU500rfmMG6dukTQ/ehbwc/UPS3q7u7+lp/1\n"
        + "bRt1KSd91rf2xremCnQcDHUh5Drt+tbUeRV9S53t9K0G6bP3t/bR6lsKUaCZtDbtpm+Z+HHSvuD9\n"
        + "7Zm0J0ba3d3f7o60vdG38Pm7z/q2+rLour6lh/SmFIRc2a5vTZ3X0bdsuahIcsq+E7jdFC67gA8M\n"
        + "lIyIsxm8ppzpyR6ZwiXwA9tIkk3cJTpiSFO47gQblmWdu1iKpu8Fmcdy1M5d5Cni22QynGDHGeoz\n"
        + "raHjQbz1Pe4gnxEymbg/At11MtUghOoEwkdCoLX87nxhm/lS9dc5epNtozexKSkdr1P0RivRG+8r\n"
        + "ehc1G+P1/4pYy11Qj1hi5UTO3u5ETrScyIljPZHjEJMadQIngnV74wRtiFeM2Ww/J3LirBNOSyfs\n"
        + "7kROnE/k2kjDCUf91QlIrM/rdomOg9EJ1ZfYWt44wa91IsfElidyouVETh7tiRwnDmkmLbW7kFaO\n"
        + "+BakfcETuTNpT4y0uzuR2x1pe3MiB5+/RX9JSza/21nA42BIW32JreWNk32RtjqRexos/ps80+Lp\n"
        + "P5Nk7PVSTwAA";
    return aa;
  }
}
