server:
  port: 8000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.46.149.32:3307/coin-exchange?serverTimezone=GMT%2B8
    username: root
    password: guofei??
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: SELECT 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: DatebookHikariCP
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    host: 172.16.171.23
    #password: lGl1688
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 10000
    lettuce:
      pool:
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
        max-active: 8

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/mapper/*Mapper.xml